### ISSUE TITLE
USER STORY: Anonymous feedback

### ISSUE THREAD

**Issue by lucijahajdu** [lucijahajdu/My-First-Agile-Project#4]
As a **user** I can **hide my identity in the poll area** so that **feedback is anonymous**

## Acceptance Criteria ##
* Acceptance Criteria 1: Chose the best time in the checkbox area
* Acceptance Criteria 2: The checkbox should be filled out by default
* Acceptance Criteria 3: Next to the checkbox submit button appears
* Acceptance Criteria 4: After submitting, submission confirmation appears

## Task ##

- [x] Create HTML and CSS for the checkbox design
- [ ] Update the controller function
- [ ] Test the completed functionality
